import Link from 'next/link';

export default function TermsOfService() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-12">
      <h1 className="text-2xl font-extrabold text-white mb-2 font-display tracking-tight">Terms of Service</h1>
      <p className="text-sm text-stone-500 mb-8">Last updated: February 14, 2026</p>

      <div className="space-y-6 text-sm text-stone-300 leading-relaxed">

        <section>
          <h2 className="text-white font-semibold mb-2">1. Agreement to Terms</h2>
          <p>
            By accessing or using Poddit&trade; (&ldquo;the Service&rdquo;), operated by
            Heathen Digital LLC (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;the Company&rdquo;),
            you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">2. Description of Service</h2>
          <p>
            Poddit is a personal podcast platform that allows users to save links, topics, and
            voice notes (&ldquo;Signals&rdquo;), which are then researched, synthesized, and
            narrated into personalized audio episodes (&ldquo;Episodes&rdquo;) using artificial
            intelligence and text-to-speech technology.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">3. Intellectual Property &mdash; Platform</h2>
          <p>
            Heathen Digital LLC owns all intellectual property rights in the Poddit platform,
            including but not limited to:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-1 text-stone-400">
            <li>The Poddit&trade; name, brand, logos, and visual identity</li>
            <li>All software, source code, and technical infrastructure</li>
            <li>AI prompts, editorial methodology, and synthesis processes</li>
            <li>The design, layout, and user interface of the application</li>
            <li>All documentation and marketing materials</li>
          </ul>
          <p className="mt-2">
            No part of the platform may be copied, reproduced, distributed, or used to create
            derivative works without the prior written consent of Heathen Digital LLC.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">4. Your Content</h2>
          <p>
            You retain full ownership of the content you submit to Poddit, including links,
            topics, text, and voice recordings (&ldquo;Your Content&rdquo;). We do not claim
            ownership over Your Content.
          </p>
          <p className="mt-2">
            By submitting Your Content to Poddit, you grant Heathen Digital LLC a non-exclusive,
            worldwide, royalty-free license to process, analyze, research, and transform Your
            Content for the sole purpose of generating your personalized Episodes and operating
            the Service. This license exists only for as long as Your Content remains on the
            platform and is revoked when you delete it.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">5. Generated Episodes</h2>
          <p>
            Episodes generated by Poddit are created for your personal, non-commercial use.
            You may listen to your Episodes on any personal device.
          </p>
          <p className="mt-2">
            You may <strong className="text-stone-200">not</strong>, without prior written
            permission from Heathen Digital LLC:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-1 text-stone-400">
            <li>Redistribute, publish, or broadcast Episodes to the public</li>
            <li>Upload Episodes to podcast directories, streaming platforms, or social media as your own content</li>
            <li>Use Episodes for any commercial purpose, including monetization</li>
            <li>Modify, remix, or create derivative works from Episodes for distribution</li>
          </ul>
          <p className="mt-2">
            Episodes may contain AI-generated research and commentary. While we strive for
            accuracy, Episodes are for informational and entertainment purposes only and
            should not be relied upon as professional, legal, financial, or medical advice.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside mt-2 space-y-1 text-stone-400">
            <li>Use the Service for any unlawful purpose</li>
            <li>Submit content that is defamatory, obscene, or violates the rights of others</li>
            <li>Attempt to reverse-engineer, decompile, or extract the platform&apos;s AI prompts, algorithms, or proprietary processes</li>
            <li>Interfere with or disrupt the Service or its infrastructure</li>
            <li>Share your account credentials or access codes with others</li>
            <li>Use automated tools to scrape, harvest, or extract data from the Service</li>
            <li>Circumvent any rate limits, access controls, or security measures</li>
          </ul>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">7. Account &amp; Access</h2>
          <p>
            Access to Poddit is provided via invitation-based access codes during the early
            access period. You are responsible for maintaining the confidentiality of your
            access credentials. We reserve the right to suspend or terminate access at our
            discretion.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">8. Early Access</h2>
          <p>
            If you are participating in the Poddit early access program, you acknowledge that:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-1 text-stone-400">
            <li>The Service is in active development and may contain bugs or incomplete features</li>
            <li>Features may change, be added, or be removed without notice</li>
            <li>Service availability is not guaranteed and may be interrupted for maintenance or updates</li>
            <li>We may collect additional feedback and usage data to improve the platform</li>
          </ul>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">9. Disclaimer of Warranties</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
            warranties of any kind, either express or implied, including but not limited to
            implied warranties of merchantability, fitness for a particular purpose, and
            non-infringement. We do not warrant that the Service will be uninterrupted,
            error-free, or that any content generated will be accurate or complete.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">10. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Heathen Digital LLC shall not be liable
            for any indirect, incidental, special, consequential, or punitive damages arising
            from your use of the Service, including but not limited to loss of data, loss of
            profits, or business interruption.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">11. Termination</h2>
          <p>
            We may suspend or terminate your access to the Service at any time, with or without
            cause. Upon termination, your right to use the Service ceases immediately. You may
            request deletion of your account and data at any time by contacting us.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">12. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will notify you of
            material changes by posting the updated Terms on this page with a revised date.
            Continued use of the Service after changes constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">13. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the
            State of Delaware, without regard to its conflict of law provisions.
          </p>
        </section>

        <section>
          <h2 className="text-white font-semibold mb-2">14. Contact</h2>
          <p>
            For questions about these Terms, contact us at{' '}
            <a href="mailto:brook@poddit.com" className="text-teal-400 hover:text-teal-300 transition-colors">
              brook@poddit.com
            </a>.
          </p>
          <p className="mt-2 text-stone-500 text-xs">
            Heathen Digital LLC
          </p>
        </section>

      </div>

      <div className="mt-12 pt-6 border-t border-stone-800/50 flex items-center justify-between">
        <Link href="/" className="text-sm text-stone-500 hover:text-stone-300 transition-colors">
          &larr; Back to Poddit
        </Link>
        <Link href="/privacy" className="text-sm text-stone-500 hover:text-stone-300 transition-colors">
          Privacy Policy &rarr;
        </Link>
      </div>
    </main>
  );
}
